package org.brahypno.esotericismtinker.network;

import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.network.NetworkEvent;
import org.brahypno.esotericismtinker.transcendence.table.menu.TranscendenceAnvilMenu;

import java.util.function.Supplier;

/**
 * Client -> server request generated by the +/- buttons on the Tuning page.
 * The client only requests a one-point change; the block entity validates and applies it.
 */
public final class TranscendenceTuningPacket {
    private final int containerId;
    private final int delta;

    public TranscendenceTuningPacket(int containerId, int delta) {
        this.containerId = containerId;
        this.delta = delta;
    }

    public TranscendenceTuningPacket(FriendlyByteBuf buffer) {
        this(buffer.readVarInt(), buffer.readByte());
    }

    public void toBytes(FriendlyByteBuf buffer) {
        buffer.writeVarInt(containerId);
        buffer.writeByte(delta);
    }

    public void handle(Supplier<NetworkEvent.Context> contextSupplier) {
        NetworkEvent.Context context = contextSupplier.get();
        context.enqueueWork(() -> {
            ServerPlayer player = context.getSender();
            if (player == null || (delta != -1 && delta != 1)) {
                return;
            }
            if (!(player.containerMenu instanceof TranscendenceAnvilMenu menu)
                || menu.containerId != containerId
                || menu.getStation() == null
                || !menu.stillValid(player)) {
                return;
            }

            if (menu.getStation().adjustTuning(delta)) {
                menu.broadcastChanges();
                menu.getStation().syncRecipe(player);
            }
        });
        context.setPacketHandled(true);
    }
}
