package org.brahypno.esotericismtinker.network;

import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.network.NetworkEvent;
import org.brahypno.esotericismtinker.transcendence.table.menu.TranscendenceAnvilMenu;

import java.util.function.Supplier;

/**
 * Client -> server request generated by the +/- buttons on the Reception page.
 * The client never writes reception data directly; the block entity validates it.
 */
public final class TranscendenceReceptionPacket {
    private final int containerId;
    private final String slotType;
    private final int delta;

    public TranscendenceReceptionPacket(int containerId, String slotType, int delta) {
        this.containerId = containerId;
        this.slotType = slotType;
        this.delta = delta;
    }

    public TranscendenceReceptionPacket(FriendlyByteBuf buffer) {
        this(buffer.readVarInt(), buffer.readUtf(64), buffer.readByte());
    }

    public void toBytes(FriendlyByteBuf buffer) {
        buffer.writeVarInt(containerId);
        buffer.writeUtf(slotType, 64);
        buffer.writeByte(delta);
    }

    public void handle(Supplier<NetworkEvent.Context> contextSupplier) {
        NetworkEvent.Context context = contextSupplier.get();
        context.enqueueWork(() -> {
            ServerPlayer player = context.getSender();
            if (player == null || delta < -1 || delta > 1 || delta == 0) {
                return;
            }
            if (!(player.containerMenu instanceof TranscendenceAnvilMenu menu)
                    || menu.containerId != containerId) {
                return;
            }
            if (menu.getStation() == null || !menu.stillValid(player)) {
                return;
            }

            if (menu.getStation().adjustReception(slotType, delta)) {
                menu.broadcastChanges();
                menu.getStation().syncRecipe(player);
            }
        });
        context.setPacketHandled(true);
    }
}
