package org.brahypno.esotericismtinker.utils.damage.profile;

public enum ProbeStepId {
    BASIC_HANDLER,
    RAW_SET_HEALTH,
    SUPER_SET_HEALTH,
    ENTITY_DATA_UNSAFE,
    PRIVATE_FIELD_UNSAFE,
    ENTITY_DATA_ABSOLUTE,
    PRIVATE_FIELD_ABSOLUTE,
    HARD_SET_HEALTH_ZERO,
    FORCE_DIE,
    LINKED_TARGET,
    LEARNED_HEALTH_FIELD,
    LEARNED_CAP_FIELD,
    METHOD_HEALTH_BACKING,
    HEALTH_BACKING_EXPLORATION,
    CAP_SOURCE_EXPLORATION
}
